local _, addonTable = ...
addonTable.object = { -- [key] = text

-- common

["Anvil"] = "Örs",
["Bonfire"] = "Kamp Ateşi",
["Elevator to Mulgor"] = "Mulgore Asansörü",
["Fierce Blaze"] = "Şiddetli Alev",
["Mailbox"] = "Posta Kutusu",
["Medium Brazier"] = "Orta Boy Mangal",
["Scorching Fire"] = "Kavurucu Ateş",
["Tall Brazier"] = "Büyük Mangal",

-- herbs

["Arthas' Tears"] = "Arthas' Tears",
["Black Lotus"] = "Black Lotus",
["Blindweed"] = "Blindweed",
["Briarthorn"] = "Briarthorn",
["Bruiseweed"] = "Bruiseweed",
["Doom Weed"] = "Doom Weed",
["Dreamfoil"] = "Dreamfoil",
["Earthroot"] = "Earthroot",
["Fadeleaf"] = "Fadeleaf",
["Firebloom"] = "Firebloom",
["Ghost Mushroom"] = "Ghost Mushroom",
["Gloom Weed"] = "Gloom Weed",
["Golden Sansam"] = "Golden Sansam",
["Goldthorn"] = "Goldthorn",
["Grave Moss"] = "Grave Moss",
["Gromsblood"] = "Gromsblood",
["Icecap"] = "Icecap",
["Khadgar's Whisker"] = "Khadgar's Whisker",
["Kingsblood"] = "Kingsblood",
["Liferoot"] = "Liferoot",
["Mageroyal"] = "Mageroyal",
["Mountain Silversage"] = "Mountain Silversage",
["Peacebloom"] = "Peacebloom",
["Plaguebloom"] = "Plaguebloom",
["Purple Lotus"] = "Purple Lotus",
["Serpentbloom"] = "Serpentbloom",
["Silverleaf"] = "Silverleaf",
["Stranglekelp"] = "Stranglekelp",
["Sungrass"] = "Sungrass",
["Violet Tragan"] = "Violet Tragan",
["Wild Steelbloom"] = "Wild Steelbloom",
["Wintersbite"] = "Wintersbite",

-- quest

["Agamand Weapon Rack"] = "Agamand Silahlığı",
["Ancient Relic"] = "Kadim Yadigar",
["Bath'rah's Cauldron"] = "Bath'rah'ın Kazanı",
["Beached Sea Creature"] = "Karaya Vurmuş Deniz Canlısı",
["Blue Raptor Nest"] = "Mavi Raptor Yuvası",
["Bloodpetal Sprout"] = "Bloodpetal Filizi",
["Bolt Charged Bramble"] = "Yıldırım Yüklü Çalı",
["Brazier of the Dormant Flame"] = "Uyuyan Alev Sunağı",
["Cache of Explosives"] = "Patlayıcı Zulası",
["Crate of Elunite"] = "Elunite Kasası",
["Damaged Crate"] = "Hasarlı Kasa",
["Dead-tooth's Strongbox"] = "Dead-tooth'un Kasası",
["Document Chest"] = "Evrak Sandığı",
["Dragonmaw Catapult"] = "Dragonmaw Mancınığı",
["Ebenezer Rustlocke's Corpse"] = "Ebenezer Rustlocke'un Cesedi",
["Flame of Uzel"] = "Uzel'in Alevi",
["Half-buried Barrel"] = "Yarı Gömülü Varil",
["Incendia Agave"] = "Incendia Agave",
["Intrepid's Locked Strongbox"] = "Intrepid'in Kilitli Çelik Kasası",
["Iron Coral"] = "Demir Mercan",
["Ironband's Strongbox"] = "Ironband'in Çelik Kasası",
["Loose Soil"] = "Gevşek Toprak",
["Matrix Punchograph 3005-A"] = "Matrix Punchograph 3005-A",
["Matrix Punchograph 3005-B"] = "Matrix Punchograph 3005-B",
["Mausoleum Seal"] = "Mezarlık Mührü",
["Mausoleum Trigger"] = "Mezarlık Tetikleyicisi",
["Musquash Root"] = "Musquash Kökü",
["Red Raptor Nest"] = "Kızıl Raptor Yuvası",
["Sealed Barrel"] = "Mühürlü Varil",
["Skeletal Sea Turtle"] = "İskelet Deniz Kaplumbağası",
["Stolen Iron Chest"] = "Çalınmış Demir Sandık",
["Stone of Outer Binding"] = "Dış Bağlama Taşı",
["Sunscorched Shell"] = "Güneşte Kavrulmuş Kabuk",
["Tear of Tilloa"] = "Tilloa'nın Gözyaşı",
["Yellow Raptor Nest"] = "Sarı Raptor Yuvası",

}